services:
  react-app:
    build: .
    image: frontend-gestor-tarefas
    restart: unless-stopped
    networks:
      frontendGestorTarefasNet:
        ipv4_address: 10.5.0.5

networks:
  frontendGestorTarefasNet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
