version: '3'
services:
  react-app:
    build: .
    image: frontend-gestor-tarefas
    labels:
      - 'traefik.enable=true' # Habilita o Traefik para esse serviço
      - 'traefik.http.routers.frontend.rule=Host(`gestor_tarefas.gmxindustrial.com.br`)' # Define a regra para o subdomínio
      - 'traefik.http.routers.frontend.entrypoints=websecure' # Define o entrypoint para HTTPS
      - 'traefik.http.routers.frontend.tls=true' # Habilita o TLS (SSL)
      - 'traefik.http.routers.frontend.tls.certresolver=letsencryptresolver' # Usa o Let's Encrypt para o certificado SSL
    networks:
      - gmlIndustrialNet # Rede do Docker que o Traefik também está usando
    ports:
      - '8080:80' # Mapeia a porta 8080 para a porta 80 do contêiner
    restart: unless-stopped

networks:
  gmlIndustrialNet:
    external: true
