version: '3'

services:
  react-app:
    build: .
    image: frontend-gestor-tarefas
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.frontend.rule=Host(`gestor_tarefas.gmxindustrial.com.br`)'
      - 'traefik.http.routers.frontend.entrypoints=websecure'
      - 'traefik.http.routers.frontend.tls=true'
      - 'traefik.http.routers.frontend.tls.certresolver=letsencryptresolver'
    networks:
      - gmlIndustrialNet
    ports:
      - '8080:80'
    restart: unless-stopped

networks:
  gmlIndustrialNet:
    external: true
