services:
  react-app:
    build: .
    image: frontend-gestor-tarefas
    ports:
      - '80:80'
    restart: unless-stopped
    networks:
      frontendGetortarefasNet:
        ipv4_address: 10.5.0.5

networks:
  frontendGetortarefasNet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
