services:
  react-app:
    build: .
    image: frontend-gestor-tarefas
    restart: unless-stopped
    ports:
      - '80:80' # Mapeia a porta 80 do container para a porta 80 do host
    networks:
      frontendGestorTarefasNet:
        ipv4_address: 10.5.0.5 # IP estático na rede Docker

networks:
  frontendGestorTarefasNet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
