// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqyltmyxladtwegamejb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xeWx0bXl4bGFkdHdlZ2FtZWpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjU2MjQwODEsImV4cCI6MjA0MTIwMDA4MX0.KDKZws72bb8dr7Q55Oqo9UgQWVij33P9P3GSEGJ5kas";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);